name: build-images-action

permissions:
  contents: read

on:
  push:
    branches:
    - 'main'
    - 'release-*'
    tags:
    - 'v*'

jobs:
  build_bmo:
    name: Build BMO container image
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: "baremetal-operator"
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  build_keepalived:
    name: Build keepalived container image
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: "keepalived"
      dockerfile-directory: resources/keepalived-docker
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
