name: E2E Fixture Test

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: E2E fixture test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Build BMO e2e Docker Image
      env:
        IMG: quay.io/metal3-io/baremetal-operator:e2e
      run: make docker

    - name: Set Up Environment and Run BMO e2e Tests
      env:
        E2E_CONF_FILE: ${{ github.workspace }}/test/e2e/config/fixture.yaml
        USE_EXISTING_CLUSTER: "false"
        GINKGO_NODES: 1
      run: make test-e2e

    - name: Upload artifacts
      uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
      with:
        name: artifacts-fixture.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
