name: E2E Fixture Test

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: E2E fixture test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - name: Install libvirt
      run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev

    - name: Build BMO e2e Docker Image
      env:
        IMG: quay.io/metal3-io/baremetal-operator:e2e
      run: make docker

    - name: Set Up Environment and Run BMO e2e Tests
      env:
        E2E_CONF_FILE: ${{ github.workspace }}/test/e2e/config/fixture.yaml
        USE_EXISTING_CLUSTER: "false"
        GINKGO_NODES: 1
      run: make test-e2e

    - name: Upload artifacts
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: artifacts-fixture.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
