name: E2E Fixture Test

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: E2E fixture test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - name: Install libvirt
      run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev

    - name: Build BMO e2e Docker Image
      env:
        IMG: quay.io/metal3-io/baremetal-operator:e2e
      run: make docker

    - name: Set Up Environment and Run BMO e2e Tests
      env:
        E2E_CONF_FILE: ${{ github.workspace }}/test/e2e/config/fixture.yaml
        USE_EXISTING_CLUSTER: "false"
        GINKGO_NODES: 1
      run: make test-e2e

    - name: Upload artifacts
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: artifacts-fixture.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
