name: E2E Test

on:
  workflow_call:
    inputs:
      bmc-protocol:
        required: true
        type: string
      runner:
        type: string
        default: "ubuntu-latest-4-cores"

permissions: {}

jobs:
  test:
    name: E2E test
    runs-on: ${{ inputs.runner }}

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install libvirt
      run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-daemon-system qemu-kvm virt-manager

    - name: Run BMO e2e Tests
      env:
        BMC_PROTOCOL: ${{ inputs.bmc-protocol }}
      # We need a new shell to pick up the new group. That is why we do the sudo -s -u $USER ...
      # Remove the pre-installed go version. We install the exact version we need.
      run: |
        sudo usermod -a -G libvirt $USER
        sudo rm /usr/bin/go
        sudo -s -u $USER bash ${{ github.workspace }}/hack/ci-e2e.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
      with:
        name: artifacts-${{ inputs.bmc-protocol }}.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
