name: E2E Fixture Test

on:
  workflow_call:

permissions: {}

jobs:
  test:
    name: E2E fixture test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - name: Install libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y libvirt-dev

    - name: Build BMO e2e Docker Image
      env:
        IMG: quay.io/metal3-io/baremetal-operator:e2e
      run: make docker

    - name: Set Up Environment and Run BMO e2e Tests
      env:
        E2E_CONF_FILE: ${{ github.workspace }}/test/e2e/config/fixture.yaml
        USE_EXISTING_CLUSTER: "false"
        GINKGO_NODES: 1
      run: make test-e2e

    - name: Upload artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: artifacts-fixture.tar.gz
        path: test/e2e/_artifacts
        if-no-files-found: error
        overwrite: false
