name: unit

on:
  workflow_call:


permissions: {}

jobs:
  golangci:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: Run unit tests
      run: make -e unit-cover
      env:
        TEST_FLAGS: "-v"
